version: "3.8"
services:
  notepad:
    build: .
    container_name: notepad
    restart: always
    ports:
     - "80:80"
    volumes:
     - notepad:/var/www/notepad/_tmp
     - ./_tmp:/var/www/notepad/_tmp
     - .:/var/www/notepad/

    environment:
    - MWN_BASE_URL=http://localhost
    # - MWN_SAVE_PATH=
    - MWN_ENCRYPTION=true
    - MWN_CRYPTO_SALT=c36g0bZfykx254eyzQNZ8SNR0gT78D89

volumes:
  notepad:
