version: "2.4"
services:
  minimalist-web-notepad:
    build: .
    container_name: minimalist-web-notepad
    restart: always
    ports:
     - "80:80"
    volumes:
     - minimalist-web-notepad:/var/www/minimalist-web-notepad/_tmp

volumes:
  minimalist-web-notepad:
